name: Release

on:
  push:
    branches:
      - dev

jobs:
  main:
    runs-on:  ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node_version:
          - 12
          - 14
        architecture:
          - x64
        include:
          - os: windows-2016
            node_version: 14
            architecture: x86
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{matrix.node_version}}
          architecture: ${{matrix.architecture}}
      - run: npm ci
      - run: npm run build
      - run: npm run tauri:build
      - run:  echo ${{secrets.GITHUB_TOKEN}}
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


